import Head from "next/head";
import styled from "styled-components";
import AppLayout from "../../components/layout/AppLayout";

interface IsAboutBlock {}

const AboutBlock = styled.div<IsAboutBlock>``;

export default function About() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <AboutBlock>
          <h1>Contact</h1>
        </AboutBlock>
      </AppLayout>
    </>
  );
}
