import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";
import AppLayout from "../../components/layout/AppLayout";
import { useRouter } from "next/router";
import { authSelector } from "../../store/auth";
import { useRecoilState } from "recoil";

interface IsLoginBlock {}

const LoginBlock = styled.div<IsLoginBlock>``;

export default function Login() {
  const router = useRouter();

  // useEffect(() => {
  //   if (window.location.href.includes("access_token")) {
  //     window.localStorage.setItem(
  //       "token",
  //       window.location.href.split("=")[1].split("&")[0] ?? "none"
  //     );
  //     router.push("/");
  //   }
  // }, []);

  const [a, b] = useRecoilState(authSelector);
  console.log(a);

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <LoginBlock></LoginBlock>
      </AppLayout>
    </>
  );
}
