import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";
import AppLayout from "../../components/layout/AppLayout";

interface IsAboutBlock {}

const AboutBlock = styled.div<IsAboutBlock>`
  width: 100%;
`;

export default function About() {
  const { sort } = useRouter().query;

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <AboutBlock>
          <h1>{sort}</h1>
        </AboutBlock>
      </AppLayout>
    </>
  );
}
