import Head from "next/head";
import styled from "styled-components";
import AppLayout from "../../components/layout/AppLayout";

interface IsCheckoutBlock {}

const CheckoutBlock = styled.div<IsCheckoutBlock>``;

export default function Checkout() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <CheckoutBlock>
          <h1>Check out</h1>
        </CheckoutBlock>
      </AppLayout>
    </>
  );
}
