import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styled from "styled-components";
import AppLayout from "../../components/layout/AppLayout";

const ProductsBlock = styled.div`
  img {
    width: 100%;
    height: auto;
  }
  h1 {
    margin-bottom: 8px;
  }
  .SizeSelector {
    display: flex;
    button {
      width: 100px;
      height: 40px;
      background: white;
      outline: 1px solid black;
      cursor: pointer;
      &:hover {
        /* background: grey; */
      }
    }
  }
  .BottomBar {
    width: calc(100% - 30px);
    height: 60px;
    position: fixed;
    bottom: 0;
    padding: 10px;
    display: flex;
    gap: 20px;
    button {
      border-radius: 2px;
      font-size: 14px;
      cursor: pointer;
    }
    .ScrapBtn {
      width: 120px;
      background: white;
      outline: 1px solid black;
    }
    .CartBtn {
      background: black;
      color: white;
    }
  }
`;

export default function Products() {
  const { id, name, price } = { id: 0, name: "name", price: 39000 };
  type IsSize = "s" | "m" | "l" | "xl";
  const [size, setSize] = useState<IsSize>();
  console.log("size: " + size);
  const onClickSizeBtn = (e: any) => {
    const { name } = e.target;
    console.log(name);
    setSize(() => name);
  };
  const onClickCartBtn = () => {
    localStorage.setItem("cart", "0");
  };

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <ProductsBlock>
          <span>{"TEE > "}</span>
          <span>NAME</span>
          <Image alt="" src={""}></Image>
          <h1>{"name"}</h1>
          <div className="SizeSelector">
            <button name="s" onClick={onClickSizeBtn}>
              S
            </button>
            <button name="m">M</button>
            <button name="l">L</button>
            <button name="xl">XL</button>
          </div>
          <div className="BottomBar">
            <button className="ScrapBtn">scrap</button>
            <button className="CartBtn">cart</button>
          </div>
        </ProductsBlock>
      </AppLayout>
    </>
  );
}
