import Head from "next/head";
import AppLayout from "../components/layout/AppLayout";
import Home from "./home";

export default function App() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <Home />
      </AppLayout>
    </>
  );
}
